### ISSUE TITLE
Does not work without RSAT tools installed

### ISSUE THREAD

**Issue by supercow** [trlinkin/puppet-domain_membership#1]
Since we're already using the powershell provider, why not use built in Powershell commands to do the reset_pw piece?

https://github.com/trlinkin/puppet-domain_membership/blob/master/manifests/init.pp#L106

I can take care of this, but working around for a customer for now.

**Comment by trlinkin** [comment]
Ping - Looking to see if there is any update. If not, I will close this soon.

I think this module still needs a better way to reset machine trusts when they fail, but I'm yet to find tools that will do it.

**Comment by trlinkin** [comment]
I'm going to assume these PRs do not exist anymore?

I'd love to have a more powershell friendly way to do this, but for now this module seems to work for plenty of people.
