### ISSUE TITLE
machine_ou syntax?

### ISSUE THREAD

**Issue by BarnumD** [trlinkin/puppet-domain_membership#10]
What is the syntax for the machine_ou variable?

**Comment by BarnumD** [comment]
I think I found the answer: `$machine_ou     = 'OU=OrgUnit; OU= Your; DC=Domain; DC=org'`

**Comment by BarnumD** [comment]
No, that doesn't seem to be it after all.. At least, the module is not creating/moving the computer account into my OU.

**Comment by damoxc** [comment]
I've found `OU=Something,OU=Something else,DC=example,DC=com` to work.

**Comment by trlinkin** [comment]
Well, this took my a while to get back to. Glad it looks like you found your answer. The syntax is fully describe in RFC-1779 (https://tools.ietf.org/html/rfc1779).

However, I'm not some monster that just links someone to an RFC and walks away, so here is a helpful doc from MS - https://msdn.microsoft.com/en-us/library/aa366101(v=vs.85).aspx
