### ISSUE TITLE
Securing domain user/password

### ISSUE THREAD

**Issue by williamayerst** [trlinkin/puppet-domain_membership#12]
Hi chaps,

What's the best way to ensure these are secret? having them encoded in plaintext somewhere doesn't fill me with confidence !

Thanks,

**Comment by juzzyau** [comment]
Take a look at hiera eyaml - https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml

**Comment by williamayerst** [comment]
Thanks! I'll check it out.

**Comment by trlinkin** [comment]
@williamayerst how did Eyaml work out?

**Comment by williamayerst** [comment]
Hi bud,

It worked perfectly fine - I'm using eyaml for all my secrets now :)
