### ISSUE TITLE
Failure waiting for PowerShell process <nnnn> to start pipe server

### ISSUE THREAD

**Issue by gpatisso** [trlinkin/puppet-domain_membership#13]
Hi,

I was wondering if you have a fix for this error I'm getting on Windows 2016. I know Windows 2016 is not in the list of supported operating systems in metadata.json but I thought you guys may be working on it.

On the first puppet run I get this:

Debug: 2016-11-30 16:05:53 +1100 C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy Bypass is running as pid: 2104
Error: /Stage[main]/Domain_membership/Exec[join_domain]: Could not evaluate: Failure waiting for PowerShell process 2104 to start pipe server
Notice: /Stage[main]/Domain_membership/Exec[reset_computer_trust]: Dependency Exec[join_domain] has failures: true
Warning: /Stage[main]/Domain_membership/Exec[reset_computer_trust]: Skipping because of failed dependencies
Notice: /Stage[main]/Domain_membership/Reboot[after]: Dependency Exec[join_domain] has failures: true
Warning: /Stage[main]/Domain_membership/Reboot[after]: Skipping because of failed dependencies

The next run works and the host joins the domain.
If I remove the host from the domain and try again same thing: first run I get the error, second run it joins the domain.
All good with the same module on Windows 2012 server.

trlinkin-domain_membership version is 1.1.2
stdlib 4.13.1
powershell 2.1.0

Thanks,
Gab

**Comment by trlinkin** [comment]
Hi, sorry for the delayed response to this one.

Is this still an issue currently? Would it possible to see the debug output when Puppet runs? The issue here is potentially something wrong with the powershell code in the module currently, but I need more information to track down the issue.

**Comment by JangamV** [comment]
Hello,
I am facing the same issue and i am struggling to resolve this.
Error: Failure waiting for the Powershell process xxxx to start pipe server.
Puppet version - 3.7.3
Powershell - 2.1.2

Please help me on this.

**Comment by trlinkin** [comment]
What version of windows, the powershell module, .net framwork?

**Comment by trlinkin** [comment]
This seems to be an issue with the Powershell module in general - https://tickets.puppetlabs.com/browse/MODULES-4748

**Comment by JangamV** [comment]
All the client machines are windows 7 64 bit
PowerShell module 2.1.2

**Comment by JangamV** [comment]
What should be the .net version?
I have seen the comments from james long back but how can we resolve this.

**Comment by trlinkin** [comment]
This issue has grown way old, is this still a problem?

**Comment by glennsarti** [comment]
This has been fixed in later PowerShell module versions.  In particular 2.1.4 fixed named pipe issues on 2008r2 and 2.1.3 fixed MODULES-4748 mentioned above.

**Comment by dhs-rec** [comment]
This is happening to me again, on various Windows versions from 2008R2 (don't ask) to 2016, with current versions of Puppet (7.20.0) and the `powershell` (5.2.0)/`pwshlib` (0.10.2) modules.
