### ISSUE TITLE
reboot options?

### ISSUE THREAD

**Issue by JasonMcMahan** [trlinkin/puppet-domain_membership#15]
This is not so much an issue, as request.
I notice in the module you are setting reboot apply to finished.
However wouldn't it better to allow the user to choose whether to apply immediately or finished?
For instance we would like it to reboot as soon as it joins the domain instead of waiting.

As i said above not an issue more a request.
Thank you for considering.

**Comment by trlinkin** [comment]
Added support for this to tag 1.2.0

I don't think I'm going to release this tag to the Forge though. I'm going to revamp the whole module to be more Puppet current. I wanted this feature in on the current major series before I make things complicated and to have a cleaner 2.0.0 release. Check it out, let me know if theres issues, thanks.
