### ISSUE TITLE
need explanation about parameter "secure_password"

### ISSUE THREAD

**Issue by htallur** [trlinkin/puppet-domain_membership#16]
"secure_password" parameter is not described. it helps if details about the parameter are provided.

**Comment by trlinkin** [comment]
That parameter has been removed in the 1.X versions. It was a bad idea and failed experiment from the beginning. I would love to tell you more about it if I recalled, but really the only useable information I have not is "don't use it."

I need to add support for the sensitive data_type. Keep an eye out for that.

**Comment by trlinkin** [comment]
I'm sorry, it isn't removed, but it should be. Still, don't use it.

**Comment by htallur** [comment]
Thanks for the response @trlinkin
