### ISSUE TITLE
support for windows 2016

### ISSUE THREAD

**Issue by htallur** [trlinkin/puppet-domain_membership#18]
current this module doesn't work on windows server 2016. is there any roadmap to support windows server 2016.

**Comment by jhonny-oliveira** [comment]
Same issue here. A fix would be welcome. Anyone has any idea on how to fix it?

**Comment by Cylindric** [comment]
@htallur and @jhonny-oliveira "doesn't work" is just a bit vague. Can you post some actual details, maybe some error messages? I've been using it and I can join 2016 servers just fine.

**Comment by jhonny-oliveira** [comment]
You are right, I was too short on my comments. Sorry!
Meanwhile, I tried dsc_xcomputer from "puppetlabs/dsc" to address the
situation and it worked. I decided not to pursue the situation any further.
Thanks anyways for your feedback!

Best regards,
Jhonny Oliveira

**Comment by htallur** [comment]
@Cylindric,  you are correct.
Issue I had is found to be not related to this module.

**Comment by trlinkin** [comment]
Ok, cool, seems like it all worked out.
