### ISSUE TITLE
Cumbersome $command and netdom

### ISSUE THREAD

**Issue by matsimon** [trlinkin/puppet-domain_membership#3]
( Possibly related to #1 )

I see you are using Get-WmiObject to construct the "cumbersome command". The question being what Windows versions the module has to Support. If you limit the module to PowerShell 2.0 compatible systems (Vista, even Server 2003 if I'm correct) then there is 'Add-Computer' which is far more legible

```Add-Computer -Domain foo -User admin@foo -oupath ... ```

Afaik 'netdom' has been deprecated for some time now, MS wants to push us to PowerShell equivalents so why not replace those pieces?

The only point is, that I don't know how to construct the $command with the optional Parameters so if i.e. OUpath isn't defined it isn't added to the command.

**Comment by trlinkin** [comment]
Closing this ticket since there is nothing useful coming out of it.

I will continue research into methods to join domains.
