### ISSUE TITLE
Error when applying configuration ( won't add to domain )

### ISSUE THREAD

**Issue by matthieudolci** [trlinkin/puppet-domain_membership#6]
Hello @trlinkin,

We are trying to use your module to add some 2012r2 in the domain via puppet, but everytime we get those errors. Could you help us out?

Thanks

Error: exit (Get-WmiObject -Class Win32_ComputerSystem).JoinDomainOrWorkGroup('domain.com','password','administrator@doamain.com',$null,1).ReturnValue returned 1332 instead of one of [0]

Error: /Stage[main]/Domain_membership/Exec[join_domain]/returns: change from not
run to 0 failed: exit (Get-WmiObject -Class Win32_ComputerSystem).JoinDomainOrWo
rkGroup('domain.com','password','administrator@domain.com',$null,1).Return
Value returned 1332 instead of one of [0]

Warning: /Stage[main]/Domain_membership/Exec[reset_computer_trust]: Skipping bec
ause of failed dependencies

**Comment by matthieudolci** [comment]
Nevermind

Just needed to change the join option...

Sorry for the ticket

**Comment by trlinkin** [comment]
Glad to hear it worked :)

**Comment by seanscottking** [comment]
@matthieudolci boo you for not saying what you changed it to 

This worked for me when setting join_option to `3` (1 + 2, according to the docs)
